### ISSUE TITLE
Bug: mkdnflow freezes neovim when I press <tab> in insert mode

### ISSUE THREAD

**Issue by jjiangweilan** [jakewvincent/mkdnflow.nvim#100]
I think this happens after I upgrade neovim to 0.8, I have disabled all the plugins in init.vim except mkdnflow. If you think it's only me hving the problem (which highly likely) could you please give me some direction to fix the issue? It only happens when I open a markdown file with mkdnflow on.

**Comment by jjiangweilan** [comment]
after I diable  `MkdnTableNextCell = {'i', '<Tab>'}` and `MkdnTablePrevCell = {'i', '<S-Tab>'}`, the program works as expected. Maybe something wrong with these two's implementation in 0.8

**Comment by jakewvincent** [comment]
I've added a workaround for this. Like you suggested, this may have something to do with Neovim 0.8, but I couldn't figure out what that might have been, so I've made an update that accomplishes the same thing as before but does it in a different way. In my testing, it is now working as expected again. Thanks for the issue, and please feel free to reopen this if this doesn't seem to be resolved after updating.

**Comment by marshallishere** [comment]
I'm with this same issue. When I press tab the resources of my neovim goes up to 5Gb of ram and 15% of my process. I have the neovim version 8.0 from the Fedora repositories and with the latest version of your plugin.

**Comment by jakewvincent** [comment]
@marshallishere, if you're positive you've recently updated the plug-in and restarted Neovim, I'll look back into this as soon as possible. Have you noticed if the issue occurs if you press tab while in a table?

**Comment by marshallishere** [comment]
I created a new index.md, placed three |, typed 'something' on the first and then pressed tab. This makes the issue. I tested the command to make a table and this works without any problems.

**Comment by jakewvincent** [comment]
Just to double check this is the same issue, are you getting the freezing when you press tab anywhere in a document while in insert mode?

**Comment by marshallishere** [comment]
When I create the table like the way I said, yes.

**Comment by jakewvincent** [comment]
Got it. What you're experiencing seems to be a separate issue, so I've opened a [new issue](https://github.com/jakewvincent/mkdnflow.nvim/issues/102) with it and will address this further there. I've reproduced it, though, so I will get this fixed as soon as possible.
