### ISSUE TITLE
Bug: Neovim freezes when pressing tab in tables without spaces

### ISSUE THREAD

**Issue by jakewvincent** [jakewvincent/mkdnflow.nvim#102]
I'm with this same issue. When I press tab the resources of my neovim goes up to 5Gb of ram and 15% of my process. I have the neovim version 8.0 from the Fedora repositories and with the latest version of your plugin.

_Originally posted by @marshallishere in https://github.com/jakewvincent/mkdnflow.nvim/issues/100#issuecomment-1284718546_

**Comment by jakewvincent** [comment]
@marshallishere this should be fixed now. Can you pull the latest update and let me know if the same thing is still happening? Thanks.

**Comment by marshallishere** [comment]
It's fixed, thanks!
