### ISSUE TITLE
Mkdnenter on empty list item

### ISSUE THREAD

**Issue by kofm** [jakewvincent/mkdnflow.nvim#104]
Sorry if this issue doesn't make sense, but I couldn't find this information in the documentation.

Using the default mapping, if I press <CR> on an empty list item, nothing happens. I expected the list item to be deleted (as in many Markdown editors). Is this intended, or am I missing something (maybe some other plugin keymapping conflicting with Mkdnflow)=

Thanks for this fantastic project

**Comment by jakewvincent** [comment]
Hi @kofm, I do actually have this built in, but the mapping isn't enabled by default (I'm afraid it might annoy people, but perhaps not having it enabled by default is actually more annoying 🙃). Check out [this section of the readme](https://github.com/jakewvincent/mkdnflow.nvim#lists)--specifically, the code snippet at the bottom of that section. That'll show you what to put into your mkdnflow config. Apologies for the delayed response!
