### ISSUE TITLE
Doing <Tab> in insert mode skips first character when indenting

### ISSUE THREAD

**Issue by mpas** [jakewvincent/mkdnflow.nvim#107]
When doing a TAB in insert mode the tab is executed but the first character is not taken into account.

![image](https://user-images.githubusercontent.com/139094/208040796-541b8e30-316d-44c1-89db-46d576d9ba18.png)

Without using the `mkdnflow` plugin, the tab is executed normally.

**Comment by jakewvincent** [comment]
Thanks for the issue! You mean this isn't what you expect when you hit tab? :D
Will push a fix ASAP.

**Comment by jakewvincent** [comment]
Actually, I'm not able to reproduce this. I tried it out with expandtab enabled and disabled. Can you tell me a little bit more about when this is happening? (Any time you push tab on the first character in the line in insert mode?) Would you mind sharing the part of your config with your editor settings?

**Comment by jakewvincent** [comment]
Also, what is your OS?

**Comment by jakewvincent** [comment]
@uvb1 sorry it took a while for me to get to this. Can you pull the latest update and let me know if this is fixed for you? Thanks!
