### ISSUE TITLE
MkdnCreateLink also runs for automatic links

### ISSUE THREAD

**Issue by hellerwach** [jakewvincent/mkdnflow.nvim#109]
First of all, I have to say great plugin.

However, I noticed that [automatic links](https://pandoc.org/MANUAL.html#automatic-links) are also affected by `MkdnCreateLink` which could be unwanted in some situations.
For example I had text with a footnote containing a link:

```markdown
Lorem ipsum[^lorem].
[^lorem]: <https://example.org>
```

I think that most pressing `<CR>` with the cursor on the link would expect the link to be opened, instead `MkdnCreateLink` is called. Maybe some distinction would be appreciated in this case.

**Comment by jakewvincent** [comment]
Thanks for creating the issue! I actually hadn't heard of automatic links before--thanks for pointing me to the pandoc reference. I agree that it would be desirable for MkdnCreateLink not to be triggered in these cases. Will take a look.

**Comment by jakewvincent** [comment]
This should be addressed now in the dev branch. Do you mind testing out the dev branch to see if this now behaves as expected?

**Comment by hellerwach** [comment]
Based on the example I have looked at, everything concerned with auto links now behaves as expected. However, there still are some issues with [reference links](https://pandoc.org/MANUAL.html#reference-links) (and footnotes), but I will have to look closer at the documentation to determine whether the fault is not with me. Will open a issue if that is not the case.

**Comment by jakewvincent** [comment]
I opened a new issue [here](https://github.com/jakewvincent/mkdnflow.nvim/issues/111) after resolving your request. If you have any requests/ideas related to footnotes, feel free to add them there.
