### ISSUE TITLE
Plus characters not recognized in unordered lists

### ISSUE THREAD

**Issue by leesoh** [jakewvincent/mkdnflow.nvim#112]
First off, thanks for all the work you've put into this extension! I really like the approach; it does almost everything I need and nothing I don't!

I've noticed some unexpected behaviour with lists. Both [GitHub Flavoured](https://github.github.com/gfm/#list-items) and [CommonMark](https://commonmark.org/help/tutorial/06-lists.html#:~:text=Unordered%20lists%20can%20use%20either,period%20.%20or%20right%20paren%20)%20.&text=Use%20any%20of%20*%20%2C%20%2B%20or,consistently%20use%20the%20same%20character.) specify that `-`, `*`, and `+` are all valid characters for a list, but `+` doesn't appear to be detected as such when using the `<C-Space>` shortcut to work with To Dos.

# Reproduction Steps

## Option 1

1. Open a new markdown file.
3. Enter `+ To do item` on a new line.
4. In Normal mode, press `<C-Space>`. Note that a to do item does not get created.

## Option 2

1. Open a new markdown file.
2. Enter `- [ ] To do item` on a new line.
3. Press enter to create a new to do item.
4. Press `<C-t`> to indent, and update the nested list item from `-` to `+`.
5. In Normal mode, press `<C-Space>`. Note that the to do item does not progress, nor does the parent task.

Hopefully this is sufficient to reproduce (and hopefully I haven't missed something obvious in the documentation!). If not, please let me know and I'd be happy to provide additional information.

**Comment by jakewvincent** [comment]
Hi @leesoh, this is right--currently, only `-` and `*` are supported as unordered list markers. However, it'll be very easy to include `+`. I'll add this in tomorrow.

**Comment by leesoh** [comment]
Thank you!!

**Comment by jakewvincent** [comment]
Just added this! Let me know if you have any issues with it--I think I got all the necessary regex patterns updated.

**Comment by leesoh** [comment]
Hi Jake! I just updated my the plugin and tried this out. It seems that `<C-space>` on a bulleted list adds `[ ]`, but so does every additional press of `<C-space>`, rather than toggling list completion.

**Comment by jakewvincent** [comment]
I forgot a couple of patterns. Can you pull the latest update and try this again?

**Comment by jakewvincent** [comment]
If you're interested in seeing the patterns I needed to update for this fix, by the way, you can check out the diffs in these commits:

https://github.com/jakewvincent/mkdnflow.nvim/commit/6f56ec8aacedbb6157b0e4fe63496e98366319a8
https://github.com/jakewvincent/mkdnflow.nvim/commit/8a88e702d916a9fc875ec26898a6e5462f64b60a

**Comment by jakewvincent** [comment]
Thanks for testing it! I'll try to fix the remaining issues today.

**Comment by jakewvincent** [comment]
All right, I've made some additional tweaks and everything appears to be working as expected on my end. Can you confirm?

**Comment by leesoh** [comment]
Looks good to me!! Thank you so much for doing this :)

**Comment by jakewvincent** [comment]
Great! No problem.
