### ISSUE TITLE
`implicit_link_transformation` doesn't appear to agree with me, in regards to my lua syntax... Little help, please. 

### ISSUE THREAD

**Issue by anoduck** [jakewvincent/mkdnflow.nvim#119]
Brilliantly created project by the way. I am always impressed when technical documentation employs a vernacular that appropriately expresses the concept being described.

I wanted to move from vimwiki to your project, because I believe it is better suited for the management of the wiki framework I am using, the [Git-Wiki](https://github.com/Drassil/git-wiki-theme). The structure of the framework is really basic. The "Index" page is your repository `README.md` file, and all the wiki pages go in the `/wiki` folder. 

Since the wiki itself determines how links are written and converted to HTML, I only need an implicit transformation to allow mkdnflow to correctly follow links. Which, as flexible as the plugin is to configure, should be a proverbial walk in the park. Unfortunately, this is not turning out to be the case, and my current comprehension of Lua syntax is more than likely to blame. 

The big kicker is when following a link on the `README.md` file is to prepend the `./wiki/` directory, while `implicit_extensions` is enabled to handle the extension bit. If you are not following a link on `README.md` then this transformation doesn't need to occur, and it is safe to use the current directory. To do this, I configured the setting for `transform_implicit` as follows. 

```lua
transform_implicit = function(input)
	local afile = vim.fn.expand('<afile>')
	local wiki_path = '~/Sandbox/wiki/'
	local wiki_index = 'README.md'
	local entry_dir = (wiki_path..'wiki/')
	local index_file = (wiki_path..wiki_index)
	local link_root = './'
	if afile == index_file then
		link_root = (entry_dir..input)
	else
		link_root = './'
	end
	return(link_root..input)
end,
```

With the above configuration, I received the following error.

```
stack traceback:
        [C]: in function 'cmd'
        ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/paths.lua:154: in function 'internal_open'
        ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/paths.lua:361: in function 'handlePath'
        ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/links.lua:639: in function 'followLink'
        ...site/pack/packer/start/mkdnflow.nvim/plugin/mkdnflow.lua:38: in function <...site/pack/packer/start/mkdnflow.nvim/plugin/mkdnflow.lua:38>
```

For the moment, I am assuming that my use of `~`  and application of paths is creating the problem. I will try make a few tweaks and see where that get's me.

**Comment by anoduck** [comment]
I have rewritten the function for implicit transformation to rely on relative path, instead of local user path, and made the appropriate changes to the perspective configuration to allow this to work. Unfortunately, the same error is occurring. 

I will require some assistance to troubleshoot the error correctly.

**Comment by jakewvincent** [comment]
Hi @anoduck, sorry for the slow reply! I think you can get what you're looking for with the following combination:

1. Set the perspective to `current`. This will cause all links to be interpreted relative to the file open in the current window. This would probably work best if the contents of your wiki folder are flat (i.e. there are no more subdirectories within that folder). If there are subdirectories, all your links would need to be relative to the currently-open file (e.g. if you've got `~/Sandbox/wiki/wiki/foo/bar.md` open and want to link to `baz.md`, which is located just outside of `foo`, the link would need to be [baz](../baz).
2. The following implicit transformation setup. It just checks to see if the current file is the index, and if it is, it prepends `wiki/` to the relative path.

```lua
transform_implicit = function(input)
    local cur_file = vim.api.nvim_buf_get_name(0)
    local output = input
    if cur_file:find("README.md$") then
        output = "wiki/" .. output
    end
    return(output)
end
```

**Comment by jakewvincent** [comment]
P.S. Thank you for the kind words!

**Comment by anoduck** [comment]
I am much a padawan to your Jedi knight programming skills. Thank you for your kindness and for lending me the attention of your mental prowess. It is indeed a rare gift to program well and explain what you have done with clarity. You will go far. Make sure you do not squander such gifts, the world needs them.

**Comment by anoduck** [comment]
Holy crab apples! That worked like butter! Ah, Snap! Awesome, pure awesomeness...

**Comment by jakewvincent** [comment]
Very glad this worked for you!

And thanks again for your generous words--I guarantee you, though, that I am no jedi knight when it comes to programming. All the Lua I learned was from persistently bashing my head against the wall for many months in the process of writing this plugin--which was really just a fancy way of procrastinating writing my dissertation. I am merely a linguist who has picked up some scripting skills over the years :D.
