### ISSUE TITLE
Bug: Follow link anchor doesn't work

### ISSUE THREAD

**Issue by jakewvincent** [jakewvincent/mkdnflow.nvim#122]
I have another similar issue. Follow link anchor doesn't work. It will always say couldn't find the heading "xxxx". I test with my own config and the config provided above.
However, if I rollback to commit "5c22d", it works with no problem. But with that commit, neovim will freeze if I press TAB unless I press \<Ctrl-c\>.

_Originally posted by @klauscc in https://github.com/jakewvincent/mkdnflow.nvim/issues/120#issuecomment-1376006470_

**Comment by jakewvincent** [comment]
![图片](https://user-images.githubusercontent.com/43649186/211569484-3d045b1b-6840-4853-8114-e4a331b472fc.png)

**Comment by jakewvincent** [comment]
@klauscc & @HUAHUAI23, can you pull the latest update and confirm that this issue is fixed for you? Thanks!

**Comment by HUAHUAI23** [comment]
thanks, it now work for anchor link, but it doesn't  seems to support Chinese char
![image](https://user-images.githubusercontent.com/43649186/212243086-f916ea18-10e3-477e-b03a-3d8f3cb88a45.png)
