### ISSUE TITLE
Bug: Link concealing (still) inadvertendly conceals some to-do statuses

### ISSUE THREAD

**Issue by jakewvincent** [jakewvincent/mkdnflow.nvim#127]
I'm still having this issue when the state is in progress:
<img width="246" alt="Screenshot 2023-01-09 at 20 21 16@2x" src="https://user-images.githubusercontent.com/1285419/211447375-e4c5c03b-3af2-4f32-9eff-b4e475967c18.png">
<img width="221" alt="Screenshot 2023-01-09 at 20 21 29@2x" src="https://user-images.githubusercontent.com/1285419/211447389-2d1a78fd-f01f-4c38-baeb-df47574eb3c8.png">

_Originally posted by @piersolenski in https://github.com/jakewvincent/mkdnflow.nvim/issues/110#issuecomment-1376635685_

**Comment by jakewvincent** [comment]
After doing some testing, it looks like it is not the concealing that is built into Mkdnflow that is causing this, but the concealing built into the markdown treesitter parsers. If I disable the treesitter modules and enable link concealing via the Mkdnflow config, the to-do status brackets are (correctly) not concealed. On the other hand, if I disable concealing via the Mkdnflow config, ensure that treesitter and the markdown parsers are installed, and run set cole=2 to enable concealing, the brackets are erroneously concealed. If you have treesitter enabled and the markdown parsers installed, and you only want the concealing provided by Mkdnflow, you'll need to disable treesitter in markdown files or remove the markdown treesitter parsers.

**Comment by sarmong** [comment]
I don't think this is the problem with the ts parser conceal rules. It has nothing to do with conceal. The parser doesn't recognize `- [-] ` as a valid task list item because it is not present in any markdown spec. And this causes conceal issue.

**Comment by jakewvincent** [comment]
@sarmong It is an "issue" with conceal in that the phenomenon of `[-]` being concealed is due to it being matched by whatever pattern/query also matches concealable segments that look similar. I agree that it's not a bug if `[-]` is not in any markdown spec.

This is pinned mainly as an FYI -- if anyone wants the expected concealment for in-progress to-do statuses, don't use the treesitter parsers (or else don't use any to-do status symbols other than ` ` and `x`).
