### ISSUE TITLE
Feature request: Support for anchor links containing UTF8 characters

### ISSUE THREAD

**Issue by jakewvincent** [jakewvincent/mkdnflow.nvim#128]
thanks, it now work for anchor link, but it doesn't  seems to support Chinese char
![image](https://user-images.githubusercontent.com/43649186/212243086-f916ea18-10e3-477e-b03a-3d8f3cb88a45.png)

_Originally posted by @HUAHUAI23 in https://github.com/jakewvincent/mkdnflow.nvim/issues/122#issuecomment-1381327771_

**Comment by jakewvincent** [comment]
@HUAHUA123 Can you pull the dev branch and let me know if you can now create + follow anchor links to headings containing non-ascii symbols? Thanks!

**Comment by HUAHUAI23** [comment]
yes, it's look ok, thamks much

https://user-images.githubusercontent.com/43649186/212519858-1915dae3-2535-46eb-b1b3-fab3d9f69765.mp4

**Comment by HUAHUAI23** [comment]
> @huahua123 Can you pull the dev branch and let me know if you can now create + follow anchor links to headings containing non-ascii symbols? Thanks!
yes, it's

https://user-images.githubusercontent.com/43649186/212519884-a585f5d3-73e0-4867-9dea-42695e2e19d0.mp4

 look ok, thamks much

**Comment by jakewvincent** [comment]
Great! I'll merge this to main soon.

**Comment by HUAHUAI23** [comment]
haha, thank you so much
