### ISSUE TITLE
"Yank Anchor" link supercedes "Yank Around Paragraph"

### ISSUE THREAD

**Issue by trev-dev** [jakewvincent/mkdnflow.nvim#129]
With Mkdnflow turned on, if I try to "yank around paragraph" (`yap`) the yank anchor binding takes over and I can no longer yank the paragraph.

I suppose I could just change this keybinding from `ya` to something else.  I can't help but wonder if this is an unintended side effect.

**Comment by jakewvincent** [comment]
Thanks for raising the issue, and sorry for the super slow response. This is good to know; I hadn't ever used `yap` so I didn't realize this would interfere. I'm going to change it to `yaa`. I don't think this feature is used enough for that to cause much of an issue.
