### ISSUE TITLE
Bug: `create_dirs` has no effect on Windows

### ISSUE THREAD

**Issue by aleksey-rowan** [jakewvincent/mkdnflow.nvim#131]
Following a link with non-existing directories does not create the missing directories. Tried explicitly setting `create_dirs` to `true` without any result.

Thank you.

- win10
- nvim 0.8.2

**Comment by aleksey-rowan** [comment]
I use [jghauser/mkdir.nvim](https://github.com/jghauser/mkdir.nvim) as a workaround for now.

**Comment by jakewvincent** [comment]
@aleksey-rowan The fix for issue #132 may have incidentally resolved this issue. It seems to be working on my test machine. Can you please let me know if this is now resolved? Thanks!

**Comment by jakewvincent** [comment]
Closing as there has been no response.
