### ISSUE TITLE
Bug: `F2 / MkdnMoveSource` doesn't work on Windows

### ISSUE THREAD

**Issue by aleksey-rowan** [jakewvincent/mkdnflow.nvim#132]
Trying to rename/move a file always fails with the "already exist" error message:

![image](https://user-images.githubusercontent.com/79934725/213361128-9a886ea7-93c1-4419-9455-a8be1e37a4fb.png)

Thank you.

- win10
- nvim 0.8.2

**Comment by jakewvincent** [comment]
Hi @aleksey-rowan, thanks for reporting this. I should have a fix up for this in the next day or two.

**Comment by jakewvincent** [comment]
@aleksey-rowan this should be fixed now. Please let me know how it works for you when you have a chance. Apologies for the delay!
