### ISSUE TITLE
jumps between file, if anchor links text contain UTF-8 chars, it will display error message

### ISSUE THREAD

**Issue by HUAHUAI23** [jakewvincent/mkdnflow.nvim#133]
https://user-images.githubusercontent.com/43649186/213619438-4286825c-4d4f-4604-a15f-b825c1a1623f.mp4

it will display error message but luckily the jumps feature seem to work ok

**Comment by jakewvincent** [comment]
Hi @HUAHUAI23, I'm not able to reproduce this either. If you could provide me with a minimal working example to test on, I'd be happy to look into it further. For example, you could provide two markdown files, one containing a link to a heading in the other file, where you are experiencing this issue. Thanks.
