### ISSUE TITLE
file link in paragraph  will not normal goto

### ISSUE THREAD

**Issue by HUAHUAI23** [jakewvincent/mkdnflow.nvim#134]
file link in paragraph will not normal goto，also file link will not add current position to jumplist （for ctrl-i ctrl-o）before jumping.

https://user-images.githubusercontent.com/43649186/214247926-e1960e15-8b47-40c0-a761-f5df2e958020.mp4

```plain
Error executing Lua callback: ...ite/pack/packer/opt/mkdnflow.nvim/lua/mkdnflow/links.lua:553: attempt to compare nil with number
stack traceback:
        ...ite/pack/packer/opt/mkdnflow.nvim/lua/mkdnflow/links.lua:553: in function 'createLink'
        ...ite/pack/packer/opt/mkdnflow.nvim/lua/mkdnflow/links.lua:648: in function 'followLink'
        .../pack/packer/opt/mkdnflow.nvim/lua/mkdnflow/wrappers.lua:66: in function 'followOrCreateLinksOrToggleFolds'
        .../pack/packer/opt/mkdnflow.nvim/lua/mkdnflow/wrappers.lua:74: in function 'multiFuncEnter'
        ...m/site/pack/packer/opt/mkdnflow.nvim/plugin/mkdnflow.lua:30: in function <...m/site/pack/packer/opt/mkdnflow.
nvim/plugin/mkdnflow.lua:30>
```

**Comment by jakewvincent** [comment]
Hi @HUAHUAI23, I'm not able to reproduce the link issue. Would you mind pasting the block of text you have in your video so I can test it in this exact context? Please also let me know if you've changed the default value for [`links.context`](https://github.com/jakewvincent/mkdnflow.nvim#%EF%B8%8F-configuration) at all.
