### ISSUE TITLE
Bug: `#` is treated as a heading when it is in a code block

### ISSUE THREAD

**Issue by sragons** [jakewvincent/mkdnflow.nvim#145]
Hello, 
The caractere '#' is considere like a title when it is present in a code section.

Exemple:

`# Test
```
# Exemple
exemple de code en markdown
````

In the code section, '#Exemple' is considere like a title:
- when you navigate with ']]'
- when you use folding fonctionality

Thank you

**Comment by jakewvincent** [comment]
@sragons this should be fixed in the latest. Thanks, and sorry for the awfully long delay.
