### ISSUE TITLE
Compat: Ensure compatibility with WhichKey when luautf8 is installed

### ISSUE THREAD

**Issue by brettmitchelldev** [jakewvincent/mkdnflow.nvim#148]
I'm not entirely sure why, but whenever I have `luautf8` installed and which-key enabled, using some builtin bindings such as `c` and `d` stop working, with which-key citing a utf-8 error when it attempts to display its popup:

```
E5108: Error executing lua ...al/share/nvim/lazy/which-key.nvim/lua/which-key/util.lua:44: invalid UTF-8 code
stack traceback:
        [C]: in function 'gsub'
        ...al/share/nvim/lazy/which-key.nvim/lua/which-key/util.lua:44: in function 't'
        ...al/share/nvim/lazy/which-key.nvim/lua/which-key/util.lua:83: in function 'parse_keys'
        ...al/share/nvim/lazy/which-key.nvim/lua/which-key/keys.lua:420: in function 'update_keymaps'
        ...al/share/nvim/lazy/which-key.nvim/lua/which-key/keys.lua:328: in function 'update'
        ...al/share/nvim/lazy/which-key.nvim/lua/which-key/init.lua:47: in function 'show'
        [string ":lua"]:1: in main chunk
```

**Comment by jakewvincent** [comment]
I've just pushed some updates that result in luautf8 no longer being needed as a luarock dependency. After updating, you should be able to remove that luarock completely, and hopefully your compatibility issue will go away. Closing this; let me know if you experience any issues with the new update.
