### ISSUE TITLE
nvim-cmp autocompletion support

### ISSUE THREAD

**Issue by kvngvikram** [jakewvincent/mkdnflow.nvim#164]
Hi,
Thanks for the plugin. 

So I want autocompletion using nvim-cmp....

because there will be many links, and i do typing errors. So instead of linking to an already existing file, i make a new file because of typing errors. autocompletion menu can help avoid that and make life easier in general.

So assuming you are not working on that already, i built a small plugin for that. You can check [cmp-mkdnflow](https://github.com/kvngvikram/cmp-mkdnflow).

It will give autocomplete options and fills `[name](path)` when you select a completion. 

So is it possible to copy this down and add it as a default feature ?
Should I make a pull request or something ? I never done that before and would need some help.

Edit: gave a pullrequest  [#165](https://github.com/jakewvincent/mkdnflow.nvim/pull/165)

**Comment by jakewvincent** [comment]
Merged the PR.
