### ISSUE TITLE
Bug: Crash while running template for wiki-style link

### ISSUE THREAD

**Issue by jayeheffernan** [jakewvincent/mkdnflow.nvim#166]
## My settings

```lua
{
      modules = {
        conceal = true,
        maps = false,
      },
      mappings = {},
      perspective = {
        priority = "root",
        root_tell = ".wikiroot",
      },
      links = {
        style = "wiki",
        name_is_source = true,
        context = 1, -- support links broken over 2 lines
        implicit_extension = "md",
      },
      new_file_template = {
        use_template = true,
      },
}
```

## What I'm trying

I have content like `[[some new file]]` in a markdown file (where `some new file.md` doesn't exist), I run `MkdnEnter` with my cursor positioned on `s` in `some`.

## What I expect

I expect it to create `some new file.md` with content `# some new file`.

## What I get

No new file/buffer, just an error. Here's the stack track (NB: line number is incorrect due to me editing the file locally):

```txt
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim:Error executing Lua callback: ...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/links.lua:192: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
	[C]: in function 'match'
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/links.lua:192: in function <...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/links.lua:171>
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/links.lua:283: in function 'getLinkPart'
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/paths.lua:126: in function 'formatTemplate'
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/paths.lua:184: in function 'internal_open'
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/paths.lua:400: in function 'handlePath'
	...cal/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/links.lua:893: in function 'followLink'
	.../share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/wrappers.lua:66: in function 'followOrCreateLinksOrToggleFolds'
	.../share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/wrappers.lua:74: in function 'multiFuncEnter'
	....local/share/nvim/lazy/mkdnflow.nvim/plugin/mkdnflow.lua:30: in function <....local/share/nvim/lazy/mkdnflow.nvim/plugin/mkdnflow.lua:30>
```

## The issue

I think the issue comes from [this line here](https://github.com/jakewvincent/mkdnflow.nvim/blob/5a9768fe09c614600fd2881f29c5cedf931f3e36/lua/mkdnflow/links.lua#L187). You already know there is no `match`, then you call `utf8.match(match, '#')`, which ends up with the `(string expected, got nil)` error.

I've tried just commenting out that `elseif` block, and that works for me (this block is handling a case with an anchor, and I'm not using an anchor in my link). I've also tried removing this part of my settings:

```lua
      new_file_template = {
        use_template = true,
      },
```

... that avoids the error as well, but I don't get the templating.

Hopefully that's enough to go off of. If you need a minimal repro LMK.

**Comment by jakewvincent** [comment]
Hi @jayeheffernan, this should be fixed now; closing the issue. Please let me know if you experience any issues after pulling the latest update. Thanks!
