### ISSUE TITLE
Bug: Anchor is lost when opening HTTP links

### ISSUE THREAD

**Issue by pipoprods** [jakewvincent/mkdnflow.nvim#168]
When opening an HTTP link containing an anchor, the base URL is opened and the anchor is lost.

**Comment by pipoprods** [comment]
Before opening a PR, I'd like your feedback on this commit @jakewvincent 

https://github.com/pipoprods/mkdnflow.nvim/commit/be695c45949a00f0c7306941a9470240c7efc88f

Could it lead to side effects?

**Comment by pipoprods** [comment]
I fixed an issue with my code. See complete diff here: https://github.com/jakewvincent/mkdnflow.nvim/compare/main...pipoprods:mkdnflow.nvim:main

**Comment by jakewvincent** [comment]
Thanks for the PR @pipoprods!
