### ISSUE TITLE
Feature: Dark-mode friendly logo

### ISSUE THREAD

**Issue by pkoch** [jakewvincent/mkdnflow.nvim#169]
This is what I see:

<img width="690" alt="Screenshot 2023-08-28 at 16 58 18" src="https://github.com/jakewvincent/mkdnflow.nvim/assets/9627/63ff84de-6ea5-437f-8795-2516c289361c">

Perhaps adding a thin white border would force legibility on both light and dark modes?

**Comment by pkoch** [comment]
Thank you for making things more accessible!

**Comment by jakewvincent** [comment]
Of course :)

On Nov 26, 2023, at 12:54 PM, Paulo Koch ***@***.***> wrote:

﻿

Thank you for making things more accessible! ❤️
