### ISSUE TITLE
open relative links to root

### ISSUE THREAD

**Issue by olesendan** [jakewvincent/mkdnflow.nvim#17]
Hi Jake.

I've been thinking if it makes sence to enhance the function 'open-relative_to'. In my workflow, I create links to documents in my 'wiki' in two ways. Either a sub link from my document, or a link from another domain(which is in other sub filer/directories from the wiki root folder. These two a used random in my wiki pages.

I suggest that instead of setting the option in config 'open_relative_to', then use some logic to define if the link is relative to the document or relative to root of the wiki.
From my thinking there should be a function which defines root, based on content i a paraent folder( should search up in the directory tree untill it finds a folder with the defined content.) the content could be defined in config ex. 'root_dir_content = {'.git', '.root', '.wiki_root'}

then the open file function could choose who to open relative files from this logic.
````
[relative sub file]('relative/sub-file.Rmd')
[relative root file]('~/relative/root-file.Rmd')
````
From my thinking this should not interfer with how we implemented files from outside the wiki, because we prefix with 'file:'

What do you think?

Greetings from denmark.
Dan Olesen

**Comment by jakewvincent** [comment]
Hi Dan--I know it's been a while since you proposed this but I think this would improve the plugin, and I hope to implement it very soon.

**Comment by jakewvincent** [comment]
@olesendan I've pushed an implementation of this to the dev branch, if you want to give it a try. The dev readme is updated (see https://github.com/jakewvincent/mkdnflow.nvim/tree/dev), so you can see the sample config there. The `links_relative_to` key in the config table now requires a table itself, where you can specify which perspective you want the plugin-to take (e.g. relative to root, relative to current file, etc.). Setup will look for a key in the `links_relative_to` table called `root_tell` which should be a string that represents the "tell" of the root directory, or in other words, a file that the plugin can use to identify which directory is the root. If you happen to try it out, let me know if there are any issues or things that you think should be changed.

**Comment by jakewvincent** [comment]
(Just pushed this to main. Please let me know if you experience any issues with the new functionality!)

**Comment by olesendan** [comment]
Hi JAke.

Sorry for my late reply. I will do some testing in the next cuple of days. If I encounter any problems, I will raise a new issue.

Greetings from denmark
Dan Olesen

**Comment by jakewvincent** [comment]
Sounds good, thanks Dan! :)

By the way, after implementing this, I realized that your suggestion was to be able to specify multiple files that together could identify the root directory. That wouldn't be too crazy to implement, but currently only one file can be provided as the "tell", just FYI.

**Comment by manu-cyber** [comment]
Hi! I’m having a bit of trouble setting this feature up in my configuration and I’m not sure what I’m doing wrong. Maybe some of you can help me pointing that out?

This is my plugin configuration:
```
~$ cat ~/.config/nvim/lua/plugins.lua
return require('packer').startup(function(use)
	use({'jakewvincent/mkdnflow.nvim',
    		rocks = 'luautf8',
    		config = function()
        		require('mkdnflow').setup({
				perspective = {
					priority = 'root',
					root_tell = '42.md',
				},
			})
    		end
	})
end)
```

And this is (obfuscated) what my file tree looks like:
```
~/notiz $ tree
.
├── 42.md
├── areas
│   └── friends
├── projects
│   ├── foo
│   │   ├── foo1
│   │   │   ├── areas
│   │   │   │   └── friends
│   │   │   └── suggestions.md
│   │   └── foo2
│   └── bar
```

So if I’m editing suggestions for project 'foo1', where my friend Bob has made a suggestion, I create a link like this:
`Suggestion from [Bob](~/areas/friends/bob.md)`. I want this to create a note into `notiz/areas/friend/`.
When I Enter on the Link though, it creates the file(tree) in my actual homedir. If I use `[Bob](areas/friends/bob.md)` instead, it is created relative to the current note.

Did I miss something obvious here? I feel like I either missed something in the config, or I’m creating the link wrong, but I can’t spot it from the documentation.
I’d appreciate any pointers :)
