### ISSUE TITLE
Bug: Links created from visual selection containing multi-byte characters are not formatted correctly

### ISSUE THREAD

**Issue by bigzhu** [jakewvincent/mkdnflow.nvim#171]
![image](https://github.com/jakewvincent/mkdnflow.nvim/assets/489815/0473b9ee-3de9-401f-b871-0db914054e33)

In virtual mode, pressing Enter to establish a link will cut off characters.

**Comment by bigzhu** [comment]
Same as #75

**Comment by bigzhu** [comment]
No, install luautf8 is not work

**Comment by jakewvincent** [comment]
Hi @bigzhu, sorry it has taken me a little while to get to this. I have an initial fix for this in a branch called `multi-byte-char-links`. Can you pull that branch and let me know if creating a link from a visual selection works as expected now? Thanks!

**Comment by jakewvincent** [comment]
Merged to main
