### ISSUE TITLE
Error disabling bib module

### ISSUE THREAD

**Issue by misaflo** [jakewvincent/mkdnflow.nvim#178]
Hi,

Since today, I have this error:

    Failed to run `config` for mkdnflow.nvim

    ...local/share/nvim/lazy/mkdnflow.nvim/lua/mkdnflow/cmp.lua:18: attempt to index field 'bib' (a boolean value)

    # stacktrace:
      - /mkdnflow.nvim/lua/mkdnflow/cmp.lua:18
      - /mkdnflow.nvim/lua/mkdnflow.lua:281 _in_ **setup**
      - .dotfiles/nvim/init.lua:539 _in_ **config**
      - .dotfiles/nvim/init.lua:156

Config:

```lua
require('mkdnflow').setup({
  modules = {
    bib = false,
  },
})
```

**Comment by jakewvincent** [comment]
Fixed, thanks!
