### ISSUE TITLE
Question: Change `MkdnFollowLink` to not create links

### ISSUE THREAD

**Issue by aorith** [jakewvincent/mkdnflow.nvim#186]
Currently I do not see how to implement this behaviour:

1. Only create links in visual mode
2. Only follow links in normal mode

```lua
      mappings = {
        MkdnEnter = { "v", "<cr>" },
        MkdnFollowLink = { "n", "<cr>" },
     }
```

With the above configuration (or with the default configuration) if I have the following markdown text:

```markdown
- List item 1
```

And the cursor is on the first column (`-` char) and press ENTER, a link is created.
If I continue to press ENTER nested links are created:

First enter:

```markdown
- [List](2023-12-30_list.md) item 1
```

Second:

```markdown
- [[List](2023-12-30_list.md)](2023-12-30_list.md) item 1
```

Would you consider to have a command/function that only follows the nearest link in the current line or does nothing if there is not link?

**Comment by jakewvincent** [comment]
Hi @aorith, sorry for the delay. There's now a config option that affects what happens if there is no link under the cursor to follow. Please see my final comment on [Issue 214](https://github.com/jakewvincent/mkdnflow.nvim/issues/214).
