### ISSUE TITLE
Incorrect <tab> behaviour in table

### ISSUE THREAD

**Issue by SebasF1349** [jakewvincent/mkdnflow.nvim#200]
I haven't change the table config, nor its keybindings. Afaik <Tab> should move to the next cell in insert mode, but it only works until the table is formatted. Once I format the table, <Tab> doesn't work as expected. Sometimes it moves to random cells and sometimes it doesn't do anything.

Here is an example with format_on_move enabled:
![wezterm-gui_Xtog4oRce0](https://github.com/jakewvincent/mkdnflow.nvim/assets/33849340/100a5a3b-eaad-48cf-91fb-10511d730a50)

To be clear: if I disable format_on_move <Tab> works. But once I run `:MkdnTableFormat` it breaks again.

**Comment by jakewvincent** [comment]
Thanks @SebasF1349, this is a bug (and I noticed it recently as well). Will take a look ASAP. Thanks for the issue.

**Comment by jakewvincent** [comment]
Hi @SebasF1349, apologies for such a delay! I just pushed a tentative fix for this. Can you pull the latest updates and let me know if this is improved?

**Comment by SebasF1349** [comment]
Looks to be fixed. Thanks! And don't worry about the delay.

I think I may have found another bug with tables, but will test a bit more and open another issue if needed.

Thanks again.
