### ISSUE TITLE
Bug: Can't create new columns in table

### ISSUE THREAD

**Issue by SebasF1349** [jakewvincent/mkdnflow.nvim#211]
Looks like `MkdnTableNewColAfter` and `MkdnTableNewColBefore` are both broken. Everytime I try to use them it shows this error:

![vivaldi_zwQboucc1P](https://github.com/jakewvincent/mkdnflow.nvim/assets/33849340/48a112fe-aee2-443a-a95c-80dcbfe4914f)

Adding rows works as expected. I tried with empty and full columns/tables and I get the same error.

Looking a bit on the error I found that in the line referenced (l 180, tables.lua) there is a `vim.api.nvim_win_get_cursor(0)` that looks to be returning a list instead of a tuple as the docs say (I'm on latest nvim nightly). But fixing that on my end then throws an error on line 512 as `match` is nil which looks correct as `string:find` only returns two values. But I'm very new to lua so I'm probably missing something.

**Comment by jakewvincent** [comment]
Thanks @SebasF1349. This should be fixed now in the latest update. Let me know if the fix is successful on your end.

**Comment by SebasF1349** [comment]
Works perfectly. Thanks a lot!
