### ISSUE TITLE
Customize MkdnNewListItem behavior

### ISSUE THREAD

**Issue by jakewvincent** [jakewvincent/mkdnflow.nvim#34]
If the cursor is in the | position in the below example and `<CR>` is mapped to MkdnNewListItem, the cursor will move to the | position in (2) without bringing the rest of the contents of (1) to the next line
```markdown
Before <CR>:
1. Foo foo foo |bar bar bar

After <CR>:
1. Foo foo foo bar bar bar
2. |
```
Expected behavior:
```markdown
Before <CR>:
1. Foo foo foo |bar bar bar

After <CR>:
1. Foo foo foo
2. |bar bar bar
```

**Comment by jakewvincent** [comment]
Fixed in commit 4da7004

**Comment by elliottt** [comment]
I'd actually like the previous behavior as well, for adding new empty entries to the list but automatically adding the `[ ]` for a todo. Is there a way to keep both behaviors?

**Comment by jakewvincent** [comment]
@elliottt yeah, I don't think it would be too difficult. I'm thinking that MkdnNewListItem could have one or two optional arguments to customize its behavior, and then if you want to use the customized behavior, you could add another mapping or remap `<CR>` to the custom command instead of the default flavor of it. How does that sound?

**Comment by elliottt** [comment]
That sounds great! Thank you :)

**Comment by jakewvincent** [comment]
@elliottt I just pushed a trial of this to the `dev` branch (commit 0b8d510181ef9ef59662a6322dbdbaf7c68a950c). Would you mind testing it out? I've added a second command, `MkdnExtendList`, which you can map to whatever you like or call directly. You probably know how, but if you're using Packer you can get the dev branch like so:
```lua
use({
    'jakewvincent/mkdnflow.nvim',
    branch = 'dev',
    -- (etc)
})
```
Let me know if everything's working as expected or if you had something slightly different in mind. If you also happen to be using `MkdnNewListItem`, let me know if you run into any errors. I refactored a couple of the list functions under the hood in the last week or so and haven't pushed those changes to `main` yet.

**Comment by elliottt** [comment]
This looks great, thank you! The only suggestion that I have is that when I run `:MkdnExtendList`, it keeps the cursor on the previous line instead of moving it to the new entry. Would that be an easy fix?

**Comment by jakewvincent** [comment]
Yes, very easy. Go ahead and update one more time. Does that seem better?

**Comment by elliottt** [comment]
Awesome, that's much better! Thanks for fixing this so quickly :)

**Comment by jakewvincent** [comment]
Great! Thanks for the suggestion :)
