### ISSUE TITLE
Mkdnflow doesn't always intuitively (de)activate

### ISSUE THREAD

**Issue by trev-dev** [jakewvincent/mkdnflow.nvim#36]
I'm noticing that my Mkdnflow config activates when I open a document directly from the command line, but if I open it from something like a fuzzy finder or telescope from within Neovim, I need to `:Mkdnflow` explicitly, which subsequently warns me that the default config is being loaded (and thus my custom config is ignored...in theory).

**Comment by jakewvincent** [comment]
I agree that this doesn't seem like ideal behavior. I have one idea... let me see what it'll take to implement it.

**Comment by jakewvincent** [comment]
I just pushed a change to the development branch that will result in your config being respected when you force-start the plugin. I'll need to do some additional work to get the plugin to activate in a reasonable if you're not opening a document directly from the command line. I probably need to add an autocommand that will activate the plugin on buffer load if the filetype is a match.

**Comment by trev-dev** [comment]
> I just pushed a change to the development branch that will result in your config being respected when you force-start the plugin. 

This is definitely working. I am very close to default, so I can't properly test, but the warning is no longer there.

> I probably need to add an autocommand that will activate the plugin on buffer load if the filetype is a match.

I could write this into my own config, or perhaps help contribute this if you're strapped for time.

I mostly just fire off these issues when I'm busy so that they're out of my head, but you are fast and it is super appreciated!!

**Comment by jakewvincent** [comment]
> I could write this into my own config, or perhaps help contribute this if you're strapped for time.
I'll be happy to work on this... I think it would be desirable default behavior anyway!
> I mostly just fire off these issues when I'm busy so that they're out of my head, but you are fast and it is super appreciated!!
Working on this plugin is how I have fun after work when there's nothing else to do, so all is good 😅

**Comment by jakewvincent** [comment]
@trev-dev I just added an autocmd (in commit c342157 on the dev branch) that should make the plugin's initialization more intuitive when you're not opening Neovim directly into a markdown file. It uses the force start function, which results in a kind of annoying message about the plugin being started. Give this a try when you get a chance and let me know if everything's working as expected.

**Comment by trev-dev** [comment]
Looks great!! I opened up a note from  Telescope and my config seems picked up and activated
