### ISSUE TITLE
Set mappings as buffer local

### ISSUE THREAD

**Issue by delafthi** [jakewvincent/mkdnflow.nvim#40]
What do you think of applying the keymaps locally to the buffer with an autocommand instead of globally? In my opinion it would be a lot nicer, if the mappings would only be applied to markdown buffers (except maybe for some keybindings, for example MkdnGoBack. However, <C-^> could also be used in a non-markdown buffer to navigate back).

**Comment by jakewvincent** [comment]
Thanks, this would be a welcome improvement. Thanks as well for teaching me about <C-^> 😆

**Comment by jakewvincent** [comment]
Pushed #41 to dev for additional testing

**Comment by jakewvincent** [comment]
Merged to main. Thanks @delafthi!
