### ISSUE TITLE
Impatient.nvim does not properly load Mkdnflow

### ISSUE THREAD

**Issue by kraxli** [jakewvincent/mkdnflow.nvim#49]
Executing `MkdnToggleToDo` or a corresponding mapping on a todo item (`- [ ] todo1`) throws the following error:

![mkdn_todotoggle](https://user-images.githubusercontent.com/8371948/173150797-96096424-b966-462c-8e02-c1c947feb6f1.png)

Nvim: 0.7
OS: Ubuntu
Shell: Zsh

**Comment by jakewvincent** [comment]
When was the last time you updated the plugin? This looks like a general message about not being able to find the `lists` module. I'm not sure why that would happen, but one possibility is you're working with an outdated version of the plugin?

**Comment by kraxli** [comment]
installed right now

**Comment by jakewvincent** [comment]
Hmm, weird. Can you show me what your mkdnflow config looks like?

**Comment by kraxli** [comment]
potentially a related error (error loading module 'mkdnflow.lists') occurs with `lua require('telekasten').insert_link({ i=true })<CR>`

![Screenshot from 2022-06-10 23-16-52](https://user-images.githubusercontent.com/8371948/173152436-9f0c5024-9bf6-4462-a49b-a7b166f1bc79.png)

**Comment by jakewvincent** [comment]
Are you using the default config? (just `require('mkdnflow').setup({})`)?

**Comment by kraxli** [comment]
Yes, but I have also tried to use the defaults explicitly

**Comment by jakewvincent** [comment]
Got it. How are you loading the plugin? In the traceback above it looks like the error occurs after the plugin is force started?

**Comment by kraxli** [comment]
unfortunately `nvim my_file.md` is also not working. I load the plugin with Packer, as you suggest in the `README.md`
```
use({'jakewvincent/mkdnflow.nvim',
     config = function()
        require('mkdnflow').setup({ })
     end
})
```
Some stuff works. E.g. the function `MkdnCreateLink` creates the link but not the file

![image](https://user-images.githubusercontent.com/8371948/173178197-cd8a439a-c208-40dc-b53a-ec5997ab8757.png)

**Comment by jakewvincent** [comment]
Interesting, thanks. I want to be able to reproduce this so I can fix it, but I'm not sure how to do so without replicating your whole config. Can you double-check the nvim version for me by pasting the output of `nvim --version` here? If you can also paste your nvim dotfiles here (or paste a link to them), that would be helpful.

**Comment by jakewvincent** [comment]
Just pushed a small change that may fix at least the mappings problem. Can you pull the update and report back?

**Comment by kraxli** [comment]
Thanks, I have pulled but still no luck :-/

**Comment by kraxli** [comment]
> nvim --version

```
nvim --version
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by jakewvincent** [comment]
I was able to reproduce this with your config, but the issue doesn't seem to be caused by mkdnflow. It has something to do with how impatient.nvim caches plugins and runs plugin setup. If I comment out the first line in your init.vim (see below), mkdnflow loads just fine. Since I'm not aware of the inner workings of impatient.nvim, I would probably recommend [filing an issue with them](https://github.com/lewis6991/impatient.nvim/issues). If you do, you can reference this issue and/or tag me.
```lua
--local impatient_ok, impatient = pcall(require, "impatient")
```

**Comment by kraxli** [comment]
Many thanks @jakewvincent for tracking this down! I will file a bug report with impatient

**Comment by kraxli** [comment]
After deleting any potential caching, it worked. I will investigate a bit further what the real root cause is.
