### ISSUE TITLE
Plugin doesn't work if you don't start nvim with a .md file. 

### ISSUE THREAD

**Issue by AndOrangutan** [jakewvincent/mkdnflow.nvim#5]
Is there any way to enable mkdnflow in an already existing nvim buffer? I use [alpha](https://github.com/goolord/alpha-nvim) and would love to open my notebook from it. 

![2021-10-27_13-10](https://user-images.githubusercontent.com/40435989/139140073-29995f1a-7255-4554-933e-3e5bd984ae0d.png)
![2021-10-27_13-11](https://user-images.githubusercontent.com/40435989/139140108-7cd04416-05a6-4963-8255-c63d2d6c8381.png)

If I just open up my index.md file with nvim your plugin works wonderfully, so it isn't an installation issue to my knowledge.

**Comment by jakewvincent** [comment]
@AndOrangutan thanks for the issue! I'll look into this ASAP and let you know when I've got it working.

**Comment by jakewvincent** [comment]
@AndOrangutan, can you update the plugin and give this a try? There's a new command that you can call, `:MkdnFlow`, which will force the plugin to start if it didn't detect a markdown filetype when you opened vim.

**Comment by AndOrangutan** [comment]
Damn that was quick, thanks a ton. Works perfectly :D
