### ISSUE TITLE
Absolute links seem to be broken for "file:" on Windows

### ISSUE THREAD

**Issue by Euthoniel** [jakewvincent/mkdnflow.nvim#52]
On Windows. Relative links work with the file prefix without issue, and markdown links using absolute path also work without error.

If I use "file:C:\Users\user\file.py" as my path, Windows tries to open the file with the default program, but starts at the location of the file I'm in. For example, if the above link was in C:\Project\Start.md, Windows would try to open the file at "C:\Project\C:\Users\user\file.py".

If I start the path with / instead of C:\, the file opens correctly with the default program, but Neovim gives the below error.

![Screenshot 2022-06-13 024829](https://user-images.githubusercontent.com/62518609/173329674-625e7546-402b-4b04-8f39-37ba35dd32b0.jpg)

**Comment by Euthoniel** [comment]
It works now with file:C:\, but Neovim still gives the same error from the image in the first post.

**Comment by jakewvincent** [comment]
This should be fixed now--can you check and report back? Thanks.

**Comment by Euthoniel** [comment]
I get a slightly different error now, see attached. The file still opens correctly.
![Screenshot 2022-06-13 153550](https://user-images.githubusercontent.com/62518609/173458879-c488f1f2-87e4-457f-b82a-cb62ece21eb8.jpg)

**Comment by jakewvincent** [comment]
Ok, I figured out where this was ultimately coming from, I think. Can you pull again and let me know if there are any errors?

**Comment by Euthoniel** [comment]
Yes, it works without errors. Thanks for fixing it, especially so quickly.

**Comment by jakewvincent** [comment]
Great! Thanks for testing it repeatedly.
