### ISSUE TITLE
Update fails ("unrelated history" error) -- see here for how to resolve

### ISSUE THREAD

**Issue by marcusatiliusregulus** [jakewvincent/mkdnflow.nvim#55]
packer update fails, trying to manually `git pull` doesn't work either due to  'unrelated history' error. please make sure to keep your git history straight as having to un- and then reinstall the whole plugin with packer is annoying. (manual `git pull --allow-unrelated-history` creates a merge conflict and just removing the repos and cloning it anew is almost imopssible on m$-windows :()

**Comment by jakewvincent** [comment]
Interesting... not sure why this would have happened, but thanks for the heads up. To me, the surest resolution here is the annoying one--comment out the plugin wherever you call `use({jakewvincent/mkdnflow.nvim})`, `PackerSync` and say "yes" to removing the plugin, uncomment, and `PackerSync` again. Leaving this issue open for now in case anyone else is experiencing this.
