### ISSUE TITLE
Interferes with due.nvim

### ISSUE THREAD

**Issue by e2oneedh2o** [jakewvincent/mkdnflow.nvim#6]
is there a way to use both mkdwnflow and due.nvim?
https://github.com/NFrid/due.nvim

**Comment by jakewvincent** [comment]
@e2oneedh2o Could you tell me in what way they're not working together? I'll install it today and do some testing myself, but I should know what exactly you're experiencing. Does one of the plugins work and not the other, or do they both not work when you try to have them active in the same buffer?

**Comment by e2oneedh2o** [comment]
@jakewvincent after looking over it again it was just user error. oops but hey it works :)

**Comment by jakewvincent** [comment]
OK, glad it works!
