### ISSUE TITLE
Can't rename files

### ISSUE THREAD

**Issue by pockethook** [jakewvincent/mkdnflow.nvim#68]
I get the following error when I press `F2` in attempt to rename a file:

``E5108: Error executing lua ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/paths.lua:408: attempt to index local 'derived_source' (a nil value)
stack traceback:
        ...e/pack/packer/start/mkdnflow.nvim/lua/mkdnflow/paths.lua:408: in function 'moveSource'
        [string ":lua"]:1: in main chunk``

**Comment by jakewvincent** [comment]
Hi @pockethook, thanks for the bug report. Can you tell me some additional details so that I can try to reproduce this? Is this happening with all links that you try to rename? What does your link text look like? Are you using the default config for the plug-in?

Thanks!

**Comment by pockethook** [comment]
Sorry, I  misread the documentation, it works fine. Great plugin :+1:

**Comment by jakewvincent** [comment]
Okay, glad it works 🙂. Can I ask what you did when the error was shown? I'd like to try to show a more informative error message in case others try the same thing.

**Comment by pockethook** [comment]
The error message comes up whenever I press `F2` and there isn't a link under the cursor.

**Comment by jakewvincent** [comment]
Thanks!
