### ISSUE TITLE
`mkdnflow.config.modules` is nil

### ISSUE THREAD

**Issue by doodleEsc** [jakewvincent/mkdnflow.nvim#72]
Error while calling lua chunk: ...m/site/pack/packer/opt/mkdnflo
w.nvim/plugin/mkdnflow.lua:137: attempt to index field 'modules' (a nil value)

`plugin/mkdnflow.lua` loaded before `mkdnflow.setup`
so the field `config` does not contain field `modules`

**Comment by jakewvincent** [comment]
Thanks. Just pushed a quick fix for this--can you update and let me know if the error goes away?

**Comment by doodleEsc** [comment]
It works fine now, thanks
