### ISSUE TITLE
Mappings don't activate on time

### ISSUE THREAD

**Issue by gregdezeeuw** [jakewvincent/mkdnflow.nvim#74]
I use Neovim-qt and Windows 10. When I start Neovim, it opens a blank buffer. I open a file via Telescope and the keys do not work. If I open a second file or reopen the first file, they start working.

If I load a file when first starting Neovim-qt, they also work without issue.

**Comment by jakewvincent** [comment]
Hi @gregdezeeuw, thanks for the issue. When you say they do not work, is it that no mappings work, or that the mappings are the default mappings (as in the issue title)?

**Comment by gregdezeeuw** [comment]
Yeah, sorry, I messed up title. None of the mappings work, either default or my own, until I open a second file or launch Neovim-qt editing a file..

**Comment by jakewvincent** [comment]
@gregdezeeuw Can you update the plugin and let me know if this issue is fixed?

**Comment by gregdezeeuw** [comment]
Yes, that fixed it.
