### ISSUE TITLE
Insert-mode mapping with leader causes lag

### ISSUE THREAD

**Issue by vandalt** [jakewvincent/mkdnflow.nvim#78]
Hi,

The default mappings for inserting table rows and columns use the `<leader>` key in insert mode. This causes a lag when the user intends to type the character of the leader key in insert mode. I have `<leader>` set to space, so this made the plugin feel slow when I first installed it.

It is not really a bug and the mappings are easy to change for users, but maybe adding a warning (or making the default mapping normal-mode only, if that is an acceptable option) would help new users facing that problem when first using the plugins?

Thanks!

**Comment by jakewvincent** [comment]
Thanks for bringing this up! I selfishly didn't think about the space-as-leader folks since I use backslash, but I went ahead and removed insert mode from the default mappings for those (in commit d9e58e701ff57da4e93bef0698f7022c0ff84a1e)--that lag is the worst.

**Comment by vandalt** [comment]
Thanks for the quick response!
