### ISSUE TITLE
Destroy link failed

### ISSUE THREAD

**Issue by nshen** [jakewvincent/mkdnflow.nvim#80]
when I press <M-CR> (Alt-Enter) 
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/181506/183092104-831cadab-220a-41ec-820e-1562e0b234a6.png">

**Comment by nshen** [comment]
MkdnMoveSource also not work

**Comment by jakewvincent** [comment]
Thanks. This is my bad--I broke these after refactoring one of the  functions they use. I will get this fixed ASAP.

**Comment by jakewvincent** [comment]
If you need to go back to a working commit right away, you can specify `commit = '739b8b93530adbd5dfb2d3abff66752637442d41'` in your `use` command for mkdnflow.

**Comment by jakewvincent** [comment]
The first (MkdnDestroyLink) is now fixed. MkdnMoveSource is temporarily disabled while I work on a fix for the issue there.

**Comment by nshen** [comment]
cool thanks.

**Comment by jakewvincent** [comment]
Just pushed a fix for the `:MkdnMoveSource` error as well. Closing this now, but please let me know if you experience any other issues with these commands. Thanks again for the bug report.

**Comment by mfiano** [comment]
`MkdnDestroyLink` will raise a stacktrace with `mkdnflow/links.lua:608: attempt to perform arithmetic on local 'row' (a nil value)` if accidentally issuing it on a non-link. Can this be silenced?

**Comment by jakewvincent** [comment]
Just pushed a small fix for this to `main`. Thanks for bringing it up.

**Comment by mfiano** [comment]
Thanks for the quick fix and wonderful plugin!

**Comment by jakewvincent** [comment]
Glad you find it useful!
