### ISSUE TITLE
autowriteall autocmd does not work when `hidden` is on

### ISSUE THREAD

**Issue by vandalt** [jakewvincent/mkdnflow.nvim#83]
Hi,

I'm not sure 100% of the cause, but when I follow a link, the autocommand suggested in the wiki (`vim.cmd('autocmd FileType markdown set autowriteall')` does not seem to automatically save the file. It does work when I do `:e someotherfile.txt` though. I think the first case does not work because I have `hidden` turned on in my config. I just wanted to point out that `vim.cmd('autocmd BufLeave *.md silent! wall')` seems to handle the case of following links, in case anyone else is facing this issue. I have both autcommands in my config now and everything works as expected. Would it be worth mentioning in the README or in the docs?

Also, I'm using both `mkdnflow.nvim` and [`zk-nvim`](https://github.com/mickael-menu/zk-nvim) at the same time, so maybe the issue occurs because of that (though it still occurs with `zk-nvim` disabled).

Thank you!

**Comment by jakewvincent** [comment]
Hi @vandalt, thanks for letting me know about this. I just took a look at `:h autowriteall` and `:h autowrite` and it looks like this is baked into `autowrite`, which is enabled when `autowriteall` is enabled:

```vimhelp
'autowrite' 'aw'	boolean	(default off)
			global
	Write the contents of the file, if it has been modified, on each
	`:next`, `:rewind`, `:last`, `:first`, `:previous`, `:stop`,
	`:suspend`, `:tag`, `:!`, `:make`, CTRL-] and CTRL-^ command; and when
	a `:buffer`, CTRL-O, CTRL-I, '{A-Z0-9}, or `{A-Z0-9} command takes one
	to another file.
	A buffer is not written if it becomes hidden, e.g. when 'bufhidden' is
	set to "hide" and `:next` is used.
	Note that for some commands the 'autowrite' option is not used, see
	'autowriteall' for that.
	Some buffers will not be written, specifically when 'buftype' is
	"nowrite", "nofile", "terminal" or "prompt".

```
I think this would be worth mentioning in the readme + help docs, so I will do that soon (or you're welcome to submit a PR if you'd like to).

**Comment by jakewvincent** [comment]
Just updated the [readme in the `dev` branch](https://github.com/jakewvincent/mkdnflow.nvim/tree/dev). I'll push it to `main` with some other changes soon. Closing this issue. Thanks again!
