### ISSUE TITLE
<CR> crashes Nvim

### ISSUE THREAD

**Issue by idr4n** [jakewvincent/mkdnflow.nvim#88]
Hi,

I noticed that if I press `<CR>` at the end of a line where there is no word/character, Nvim stops responding.

Say I'm editing this line (| represents the position of the cursor):

`- Some line here: |`

Then if I press `<CR>` Nvim stops responding somehow. However, if I press `<CR>` while at the beginning of a line (empty or not) or while on top of a character/word/selection, then it works as expected and it adds a link such as `[](2022-08-30_.md)`.

**Comment by jakewvincent** [comment]
@idr4n I just pushed an update that I think should fix this. Can you pull the update and let me know if it is fixed for you?

**Comment by idr4n** [comment]
I just checked and although it fixes the issue of pressing enter at the end of the line, it doesn't work on empty lines. So basically it does work anywhere on a non-empty line, but not working on complete empty lines. I get this error:

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/20104703/187654008-93ebd5d6-8261-4983-aac4-599ccdc93a7b.png">

**Comment by jakewvincent** [comment]
Ah, thanks. Should be fixed now, if you can pull the latest update.

**Comment by idr4n** [comment]
Yes, it is working now as expected. Thanks for this!
