### ISSUE TITLE
disability of formatting table when "\|" not perfoming as a split sign exists in table .

### ISSUE THREAD

**Issue by ttw1018** [jakewvincent/mkdnflow.nvim#90]
As the tilte says.

**Comment by jakewvincent** [comment]
Hi, thanks for reporting this. I think this should be a relatively easy fix, but it might take me a couple days to get to it.

**Comment by jakewvincent** [comment]
Fixed in commit 69f8d9ab9d6c62cdf92a692e3ac4d21f5cb40cd6. Let me know if you have any issues with this.
