### ISSUE TITLE
MkdnToggleToDo first state issue

### ISSUE THREAD

**Issue by domas-v** [jakewvincent/mkdnflow.nvim#91]
Hi there! Thank you for your work. I love the plugin.

I'm having issues with the `MkdnToggleToDo`
I have configured the `to_do.symbols` table to have three icons, installed the recommended luarocks module, but there is one thing that doesn't work for me - inserting a todo state to a bullet list. It always inserts the default (`[ ]`) not started state first. Then, when I want to toggle the started state, it does not work and says *Not a to-do list item!*. If I then insert the state icon manually, it starts to work. I have added the screen recording and my mkdnflow config below. Hope you can help!

Hopefully you can see:
https://user-images.githubusercontent.com/30794128/189524259-3e8d7730-df9b-4f37-8433-c1d898f76aa5.mov

My config:

```
require('mkdnflow').setup({
    perspective = {
        priority = 'root',
        fallback = 'first',
        root_tell = 'index.md',
        nvim_wd_heel = true
    },
    links = {
        style = 'markdown',
        conceal = false,
        implicit_extension = nil,
        transform_implicit = false,
        transform_explicit = function(text)
            text = text:gsub(" ", "-")
            return(text)
        end
    },
    to_do = {
        symbols = {'', '', ''},
        update_parents = true,
        -- not_started = '',
        -- in_progress = '',
        -- complete = ''
    },
    mappings = {
        MkdnTagSpan = {'v', '<M-CR>'},
        MkdnYankAnchorLink = {'n', '<leader>ml'},
        MkdnYankFileAnchorLink = {'n', '<leader>mL'},
        MkdnToggleToDo = {{'n', 'v'}, '<leader>mt'},
        MkdnUpdateNumbering = {'n', '<leader>mn'},
        MkdnTableNewRowBelow = {'n', '<leader>mr'},
        MkdnTableNewRowAbove = {'n', '<leader>mR'},
        MkdnTableNewColAfter = {'n', '<leader>mc'},
        MkdnTableNewColBefore = {'n', '<leader>mC'},
        MkdnFoldSection = {'n', '<leader>mf'},
        MkdnUnfoldSection = {'n', '<leader>mF'}
    }
})
```

**Comment by jakewvincent** [comment]
Hi @domas-v, sorry for the delay on this easy fix. Can you pull the latest update and try again?
