### ISSUE TITLE
Feature request: Support angle brackets surrounding link sources

### ISSUE THREAD

**Issue by jjiangweilan** [jakewvincent/mkdnflow.nvim#92]
I have many files that use whitespace as part of the file name. And the rule is written in the [spec](https://spec.commonmark.org/0.30/)

`[Clustered Deferred and Forward Shading](</docs/Clustered Deferred and Forward Shading.pdf>)` <- if I <enter> at this, mkdnflow gives an error, because it sees angle brackets as part of the path
![image](https://user-images.githubusercontent.com/13493742/189624589-e44c53e3-9134-403e-b099-1dd6cbd31a5b.png)

**Comment by jakewvincent** [comment]
Hi @jjiangweilan, sorry for the delay on this. I'm hoping to implement this soon.

**Comment by jakewvincent** [comment]
@jjiangweilan, would you mind pulling the latest update and letting me know if this is now working as expected?

**Comment by jjiangweilan** [comment]
> @jjiangweilan, would you mind pulling the latest update and letting me know if this is now working as expected?

Thanks for taking time to implement this! I can confirm it works. I tested normal links and links starting with `file:`
