### ISSUE TITLE
wrappers.lua:56 Attempt to index field 'modules' a nil value

### ISSUE THREAD

**Issue by ibnishak** [jakewvincent/mkdnflow.nvim#94]
OS: Arch Linux
NVIM: 0.7.2

Packer Config:
```lua
use({'jakewvincent/mkdnflow.nvim',
    ft = "markdown",
    config = function()
    require('mkdnflow').setup()
    end
})
```

Error on running `:MkdnEnter`. 
<CR> key does nothing either.

**Comment by ibnishak** [comment]
Closing this issue: Problem was that I had [telekasten](https://github.com/renerocksai/telekasten.nvim) plugin which was conflicting with mkdnflow. Removing telekasten solved the issue.

Great plugin you got here.

**Comment by jakewvincent** [comment]
Happy to hear you got it resolved! Thanks for the update.
