### ISSUE TITLE
README.md is a little mixed up

### ISSUE THREAD

**Issue by lumpsoid** [jakewvincent/mkdnflow.nvim#98]
> `links` (dictionary-like table)
> - `links.name_is_source`
>     - true: Wiki-style links will be created with separate name and source (e.g. [[link-to-source|Link]] will display as "Link" and go to a file named "link-to-source.md")
>     - false: Wiki-style links will be created with the source and name being the same (e.g. [[Link]] will display as "Link" and go to a file named "Link.md")

this part of the documentation is mixed up, because the true option does what is described as false

and it would be nice, if documentation have `(default)` marks after default options, because without it, you have to keep turning the page to understand what I want to change and what needs to be prescribed, as it is not default, and what to leave as it is

what is the best way to do this?
download this git for myself, then create a branch where I change how I would like to improve the readme, and create a pull request, that you can review?

**Comment by lumpsoid** [comment]
or create branch for this update from `dev` branch?

**Comment by jakewvincent** [comment]
Hi @lumpsoid, thanks for the issue. I'll get this fixed in the readme today. I've actually already started adding "default" next to default options but it's currently only in the dev branch readme while I test some other updates. I'll merge it to main soon.

**Comment by jakewvincent** [comment]
Fixed the description. As noted above, labels for default values will be added soon (already added in dev branch at time of issue creation). Thanks again for pointing this out @lumpsoid!

**Comment by lumpsoid** [comment]
Thank you for your responsiveness!
